db:
  image: mysql:5.6
  env_file: .env.db
  ports:
    - "13306:3306"
web:
  build: .
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  env_file: .env.web